name: iptv_player
description: "Reproductor IPTV con autenticaci√≥n"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  pocketbase: ^0.18.0
  video_player: ^2.8.1
  chewie: ^1.7.4
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  http: ^1.1.0
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true